# Based off of <https://mozilla.github.io/cargo-vet/multiple-repositories.html>
name: CI
on:
  push:
  pull_request:
  schedule:
    # Every hour
    - cron:  '0 * * * *'

permissions:
  contents: write

jobs:
  aggregate:
    name: Aggregate Dependencies
    runs-on: ubuntu-latest
    container: rust:latest
    env:
      CARGO_VET_VERSION: 0.9.0
    steps:
    - uses: actions/checkout@master
    - uses: actions/cache@v2
      id: cache-vet
      with:
        path: /usr/local/cargo/bin/cargo-vet
        key: cargo-vet-${{ env.CARGO_VET_VERSION }}
    - name: Install the cargo-vet binary, if needed
      if: ${{ steps.cache-vet.outputs.cache-hit != 'true' }}
      run: cargo install --version ${{ env.CARGO_VET_VERSION }} cargo-vet
    - name: Invoke cargo-vet aggregate
      run: cargo vet aggregate --output-file audits.toml sources.list
    - name: Commit changes (if any)
      run: |
        git config --global user.name "cargo-vet[bot]"
        git config --global user.email "cargo-vet-aggregate@invalid"
        git config --global --add safe.directory '*'
        git add audits.toml
        git commit -m "Aggregate new audits" || true
    - name: Push changes (if any) for scheduled runs
      if: github.event.schedule
      run: git push origin main
